// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protocol_Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Protocol {

  /// <summary>Holder for reflection information generated from Protocol_Enum.proto</summary>
  public static partial class ProtocolEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Protocol_Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQcm90b2NvbF9FbnVtLnByb3RvEghQcm90b2NvbBofZ29vZ2xlL3Byb3Rv",
            "YnVmL3RpbWVzdGFtcC5wcm90byqkBAoFTXNnSWQSDwoLQ19QSU5HQ0hFQ0sQ",
            "ABIPCgtTX1BPTkdDSEVDSxABEg0KCVNfQ09OTkVDVBACEhAKDENfUExBWUVS",
            "SU5GTxADEgoKBkNfQ0hBVBAEEgoKBlNfQ0hBVBAFEgsKB0NfUkVBRFkQBhIL",
            "CgdTX1JFQURZEAcSCwoHQ19TVEFSVBAIEhIKDlNfTE9BRElOR1NUQVJUEAkS",
            "CgoGQ19NT1ZFEAoSCgoGU19NT1ZFEAsSDgoKQ19FWElUUk9PTRAMEg4KClNf",
            "RVhJVFJPT00QDRIUChBTX0NIQU5HRVJPT01JTkZPEA4SEAoMQ19DUkVBVEVS",
            "T09NEA8SFgoSQ19DUkVBVEVPUkpPSU5ST09NEBASFAoQQ19FTlRFUk1BVENI",
            "Uk9PTRAREhQKEFNfRU5URVJNQVRDSFJPT00QEhIOCgpDX1JPT01MSVNUEBMS",
            "DgoKU19ST09NTElTVBAUEg4KClNfUk9PTUlORk8QFRIVChFDX0xPQURJTkdD",
            "T01QTEVURRAWEhEKDVNfSU5HQU1FU1RBUlQQFxIMCghDX0lOVklURRAYEgwK",
            "CFNfSU5WSVRFEBkSEAoMU19TUEFXTkVORU1ZEBoSDwoLU19FUlJPUkNPREUQ",
            "GxISCg5DX0VYSVRHQU1FUk9PTRAcEhIKDlNfRVhJVEdBTUVST09NEB0SDwoL",
            "Q19FTkVNWU1PVkUQHhIPCgtTX0VORU1ZTU9WRRAfKkEKDkdhbWVPYmplY3RU",
            "eXBlEggKBE5PTkUQABIKCgZQTEFZRVIQARIJCgVFTkVNWRACEg4KClBST0pF",
            "Q1RJTEUQAyo4Cg1DcmVhdHVyZVN0YXRlEggKBElETEUQABIICgRNT1ZFEAES",
            "CQoFU0tJTEwQAhIICgRERUFEEANCG6oCGEdvb2dsZS5Qcm90b2J1Zi5Qcm90",
            "b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Protocol.MsgId), typeof(global::Google.Protobuf.Protocol.GameObjectType), typeof(global::Google.Protobuf.Protocol.CreatureState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("C_PINGCHECK")] CPingcheck = 0,
    [pbr::OriginalName("S_PONGCHECK")] SPongcheck = 1,
    [pbr::OriginalName("S_CONNECT")] SConnect = 2,
    [pbr::OriginalName("C_PLAYERINFO")] CPlayerinfo = 3,
    [pbr::OriginalName("C_CHAT")] CChat = 4,
    [pbr::OriginalName("S_CHAT")] SChat = 5,
    [pbr::OriginalName("C_READY")] CReady = 6,
    [pbr::OriginalName("S_READY")] SReady = 7,
    [pbr::OriginalName("C_START")] CStart = 8,
    [pbr::OriginalName("S_LOADINGSTART")] SLoadingstart = 9,
    [pbr::OriginalName("C_MOVE")] CMove = 10,
    [pbr::OriginalName("S_MOVE")] SMove = 11,
    [pbr::OriginalName("C_EXITROOM")] CExitroom = 12,
    [pbr::OriginalName("S_EXITROOM")] SExitroom = 13,
    [pbr::OriginalName("S_CHANGEROOMINFO")] SChangeroominfo = 14,
    [pbr::OriginalName("C_CREATEROOM")] CCreateroom = 15,
    [pbr::OriginalName("C_CREATEORJOINROOM")] CCreateorjoinroom = 16,
    [pbr::OriginalName("C_ENTERMATCHROOM")] CEntermatchroom = 17,
    [pbr::OriginalName("S_ENTERMATCHROOM")] SEntermatchroom = 18,
    [pbr::OriginalName("C_ROOMLIST")] CRoomlist = 19,
    [pbr::OriginalName("S_ROOMLIST")] SRoomlist = 20,
    [pbr::OriginalName("S_ROOMINFO")] SRoominfo = 21,
    [pbr::OriginalName("C_LOADINGCOMPLETE")] CLoadingcomplete = 22,
    [pbr::OriginalName("S_INGAMESTART")] SIngamestart = 23,
    [pbr::OriginalName("C_INVITE")] CInvite = 24,
    [pbr::OriginalName("S_INVITE")] SInvite = 25,
    [pbr::OriginalName("S_SPAWNENEMY")] SSpawnenemy = 26,
    [pbr::OriginalName("S_ERRORCODE")] SErrorcode = 27,
    [pbr::OriginalName("C_EXITGAMEROOM")] CExitgameroom = 28,
    [pbr::OriginalName("S_EXITGAMEROOM")] SExitgameroom = 29,
    [pbr::OriginalName("C_ENEMYMOVE")] CEnemymove = 30,
    [pbr::OriginalName("S_ENEMYMOVE")] SEnemymove = 31,
  }

  public enum GameObjectType {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("PLAYER")] Player = 1,
    [pbr::OriginalName("ENEMY")] Enemy = 2,
    [pbr::OriginalName("PROJECTILE")] Projectile = 3,
  }

  public enum CreatureState {
    [pbr::OriginalName("IDLE")] Idle = 0,
    [pbr::OriginalName("MOVE")] Move = 1,
    [pbr::OriginalName("SKILL")] Skill = 2,
    [pbr::OriginalName("DEAD")] Dead = 3,
  }

  #endregion

}

#endregion Designer generated code
