// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protocol_Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Protocol {

  /// <summary>Holder for reflection information generated from Protocol_Enum.proto</summary>
  public static partial class ProtocolEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Protocol_Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQcm90b2NvbF9FbnVtLnByb3RvEghQcm90b2NvbBofZ29vZ2xlL3Byb3Rv",
            "YnVmL3RpbWVzdGFtcC5wcm90byq1BgoFTXNnSWQSDwoLQ19QSU5HQ0hFQ0sQ",
            "ABIPCgtTX1BPTkdDSEVDSxABEg0KCUNfQ09OTkVDVBACEg0KCVNfQ09OTkVD",
            "VBADEgoKBkNfQ0hBVBAEEgoKBlNfQ0hBVBAFEgsKB0NfUkVBRFkQBhILCgdT",
            "X1JFQURZEAcSCwoHQ19TVEFSVBAIEhIKDlNfTE9BRElOR1NUQVJUEAkSCgoG",
            "Q19NT1ZFEAoSCgoGU19NT1ZFEAsSDgoKQ19FWElUUk9PTRAMEg4KClNfRVhJ",
            "VFJPT00QDRIQCgxDX0NSRUFURVJPT00QDxIWChJDX0NSRUFURU9SSk9JTlJP",
            "T00QEBIUChBDX0VOVEVSTUFUQ0hST09NEBESFAoQU19FTlRFUk1BVENIUk9P",
            "TRASEhMKD1NfTUFUQ0hST09NSU5GTxAVEhUKEUNfTE9BRElOR0NPTVBMRVRF",
            "EBYSEQoNU19JTkdBTUVTVEFSVBAXEhAKDFNfU1BBV05FTkVNWRAaEg8KC1Nf",
            "RVJST1JDT0RFEBsSEgoOQ19FWElUR0FNRVJPT00QHBISCg5TX0VYSVRHQU1F",
            "Uk9PTRAdEg8KC0NfRU5FTVlNT1ZFEB4SDwoLU19FTkVNWU1PVkUQHxISCg5T",
            "X0dBTUVST09NSU5GTxAgEhYKEUNfQ1JFQVRFUEFSVFlST09NEMgBEhUKEENf",
            "RU5URVJQQVJUWVJPT00QyQESFQoQU19FTlRFUlBBUlRZUk9PTRDKARIUCg9D",
            "X0VYSVRQQVJUWVJPT00QywESFAoPU19QQVJUWVJPT01JTkZPEMwBEhQKD1Nf",
            "RVhJVFBBUlRZUk9PTRDNARINCghDX0lOVklURRDOARINCghTX0lOVklURRDP",
            "ARIRCgxTX01BVENIU1RBUlQQrAISDAoHQ19JTlBVVBCRAxIMCgdTX0lOUFVU",
            "EJIDEgoKBUNfRVhQEJMDEgoKBVNfRVhQEJQDEg4KCVNfTEVWRUxVUBCVAxIP",
            "CgpDX05FV1NLSUxMEJYDEhMKDkNfVVBHUkFERVNLSUxMEJcDEhIKDVNfU0tJ",
            "TExTRUxFQ1QQmAMSFAoPU19MRVZFTFVQRklOSVNIEJkDKkEKDkdhbWVPYmpl",
            "Y3RUeXBlEggKBE5PTkUQABIKCgZQTEFZRVIQARIJCgVFTkVNWRACEg4KClBS",
            "T0pFQ1RJTEUQAyo4Cg1DcmVhdHVyZVN0YXRlEggKBElETEUQABIICgRNT1ZF",
            "EAESCQoFU0tJTEwQAhIICgRERUFEEAMqJAoNRW5lbXlNb3ZlTW9kZRIJCgVM",
            "T0NBTBAAEggKBFNZTkMQAUIbqgIYR29vZ2xlLlByb3RvYnVmLlByb3RvY29s",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Protocol.MsgId), typeof(global::Google.Protobuf.Protocol.GameObjectType), typeof(global::Google.Protobuf.Protocol.CreatureState), typeof(global::Google.Protobuf.Protocol.EnemyMoveMode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("C_PINGCHECK")] CPingcheck = 0,
    [pbr::OriginalName("S_PONGCHECK")] SPongcheck = 1,
    [pbr::OriginalName("C_CONNECT")] CConnect = 2,
    [pbr::OriginalName("S_CONNECT")] SConnect = 3,
    [pbr::OriginalName("C_CHAT")] CChat = 4,
    [pbr::OriginalName("S_CHAT")] SChat = 5,
    [pbr::OriginalName("C_READY")] CReady = 6,
    [pbr::OriginalName("S_READY")] SReady = 7,
    [pbr::OriginalName("C_START")] CStart = 8,
    [pbr::OriginalName("S_LOADINGSTART")] SLoadingstart = 9,
    [pbr::OriginalName("C_MOVE")] CMove = 10,
    [pbr::OriginalName("S_MOVE")] SMove = 11,
    [pbr::OriginalName("C_EXITROOM")] CExitroom = 12,
    [pbr::OriginalName("S_EXITROOM")] SExitroom = 13,
    [pbr::OriginalName("C_CREATEROOM")] CCreateroom = 15,
    [pbr::OriginalName("C_CREATEORJOINROOM")] CCreateorjoinroom = 16,
    [pbr::OriginalName("C_ENTERMATCHROOM")] CEntermatchroom = 17,
    [pbr::OriginalName("S_ENTERMATCHROOM")] SEntermatchroom = 18,
    [pbr::OriginalName("S_MATCHROOMINFO")] SMatchroominfo = 21,
    [pbr::OriginalName("C_LOADINGCOMPLETE")] CLoadingcomplete = 22,
    [pbr::OriginalName("S_INGAMESTART")] SIngamestart = 23,
    [pbr::OriginalName("S_SPAWNENEMY")] SSpawnenemy = 26,
    [pbr::OriginalName("S_ERRORCODE")] SErrorcode = 27,
    [pbr::OriginalName("C_EXITGAMEROOM")] CExitgameroom = 28,
    [pbr::OriginalName("S_EXITGAMEROOM")] SExitgameroom = 29,
    [pbr::OriginalName("C_ENEMYMOVE")] CEnemymove = 30,
    [pbr::OriginalName("S_ENEMYMOVE")] SEnemymove = 31,
    [pbr::OriginalName("S_GAMEROOMINFO")] SGameroominfo = 32,
    [pbr::OriginalName("C_CREATEPARTYROOM")] CCreatepartyroom = 200,
    [pbr::OriginalName("C_ENTERPARTYROOM")] CEnterpartyroom = 201,
    [pbr::OriginalName("S_ENTERPARTYROOM")] SEnterpartyroom = 202,
    [pbr::OriginalName("C_EXITPARTYROOM")] CExitpartyroom = 203,
    [pbr::OriginalName("S_PARTYROOMINFO")] SPartyroominfo = 204,
    [pbr::OriginalName("S_EXITPARTYROOM")] SExitpartyroom = 205,
    [pbr::OriginalName("C_INVITE")] CInvite = 206,
    [pbr::OriginalName("S_INVITE")] SInvite = 207,
    [pbr::OriginalName("S_MATCHSTART")] SMatchstart = 300,
    [pbr::OriginalName("C_INPUT")] CInput = 401,
    [pbr::OriginalName("S_INPUT")] SInput = 402,
    [pbr::OriginalName("C_EXP")] CExp = 403,
    [pbr::OriginalName("S_EXP")] SExp = 404,
    [pbr::OriginalName("S_LEVELUP")] SLevelup = 405,
    [pbr::OriginalName("C_NEWSKILL")] CNewskill = 406,
    [pbr::OriginalName("C_UPGRADESKILL")] CUpgradeskill = 407,
    [pbr::OriginalName("S_SKILLSELECT")] SSkillselect = 408,
    [pbr::OriginalName("S_LEVELUPFINISH")] SLevelupfinish = 409,
  }

  public enum GameObjectType {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("PLAYER")] Player = 1,
    [pbr::OriginalName("ENEMY")] Enemy = 2,
    [pbr::OriginalName("PROJECTILE")] Projectile = 3,
  }

  public enum CreatureState {
    [pbr::OriginalName("IDLE")] Idle = 0,
    [pbr::OriginalName("MOVE")] Move = 1,
    [pbr::OriginalName("SKILL")] Skill = 2,
    [pbr::OriginalName("DEAD")] Dead = 3,
  }

  public enum EnemyMoveMode {
    [pbr::OriginalName("LOCAL")] Local = 0,
    [pbr::OriginalName("SYNC")] Sync = 1,
  }

  #endregion

}

#endregion Designer generated code
